// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "HelloServerlessGoa": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/tleyden/serverless-forms/design
// --out=$(GOPATH)/src/github.com/tleyden/serverless-forms/goa-generated
// --version=v1.2.0-dirty

package client

import (
	"github.com/goadesign/goa"
	"net/http"
)

// Hello World (default view)
//
// Identifier: application/vnd.hello+json; view=default
type Hello struct {
	// What was said
	Hello string `form:"hello" json:"hello" xml:"hello"`
}

// Validate validates the Hello media type instance.
func (mt *Hello) Validate() (err error) {
	if mt.Hello == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "hello"))
	}
	return
}

// DecodeHello decodes the Hello instance encoded in resp body.
func (c *Client) DecodeHello(resp *http.Response) (*Hello, error) {
	var decoded Hello
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}
