// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "HelloServerlessGoa": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/tleyden/serverless-forms/design
// --out=$(GOPATH)/src/github.com/tleyden/serverless-forms/goa-generated
// --version=v1.2.0-dirty

package app

import (
	"fmt"
	"strings"
)

// HelloHref returns the resource href.
func HelloHref(whatToSay interface{}) string {
	paramwhatToSay := strings.TrimLeftFunc(fmt.Sprintf("%v", whatToSay), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/hello/%v", paramwhatToSay)
}
