// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "HelloServerlessGoa": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/tleyden/serverless-forms/design
// --out=$(GOPATH)/src/github.com/tleyden/serverless-forms/goa-generated
// --version=v1.2.0-dirty

package app

import (
	"github.com/goadesign/goa"
)

// Hello World (default view)
//
// Identifier: application/vnd.hello+json; view=default
type Hello struct {
	// What was said
	Hello string `form:"hello" json:"hello" xml:"hello"`
}

// Validate validates the Hello media type instance.
func (mt *Hello) Validate() (err error) {
	if mt.Hello == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "hello"))
	}
	return
}
